# Generated by Django 4.1.5 on 2023-02-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao_de_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('empresa_avaliada', models.CharField(max_length=200)),
                ('lugar_de_coleta', models.CharField(max_length=200)),
                ('formulario_de_amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.parametro')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_de_Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitacao_de_serviço', models.CharField(max_length=200)),
                ('tipo_de_amostra', models.CharField(max_length=200)),
                ('data_de_coleta', models.DateField()),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.parametro')),
            ],
        ),
    ]
