# Generated by Django 4.1.5 on 2023-02-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_solicitacao_de_servico_formulario_de_amostra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_de_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
